spring:
  config:
    import: ""
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        request.timeout.ms: 500
        delivery.timeout.ms: 1000
        max.block.ms: 1000
logging:
  config:
kafka:
  producer:
    send-timeout-ms: 2000
origin:
  host: localhost
  domain: local
server:
  port: 8100

example-one:
  consumer-enabled: true
  group-id: movie-one-group-id
  topic: example-topic-one
example-two:
  consumer-enabled: true
  group-id: movie-two-group-id
  topic: example-topic-two

