version: "3.6"

services:
  postgres:
    container_name: dimas-postgres
    restart: "no"
    image: postgres:13.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dimas-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
